# Fundamental Analysis in Python

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

In [2]:
symbol = '^GSPC'
stock = yf.Ticker(symbol)

In [3]:
stock.info

{'previousClose': 2529.19,
 'regularMarketOpen': 2436.5,
 'twoHundredDayAverage': 3101.0874,
 'trailingAnnualDividendYield': None,
 'payoutRatio': None,
 'volume24Hr': None,
 'regularMarketDayHigh': 2453.57,
 'navPrice': None,
 'averageDailyVolume10Day': 8094458571,
 'totalAssets': None,
 'regularMarketPreviousClose': 2529.19,
 'fiftyDayAverage': 3114.999,
 'trailingAnnualDividendRate': None,
 'open': 2436.5,
 'toCurrency': None,
 'averageVolume10days': 8094458571,
 'expireDate': None,
 'yield': None,
 'algorithm': None,
 'dividendRate': None,
 'exDividendDate': None,
 'beta': None,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 2280.52,
 'priceHint': 2,
 'currency': 'USD',
 'regularMarketVolume': 901816472,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': None,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 4540914918,
 'priceToSalesTrailing12Months': None,
 'dayLow': 2280.52,
 'ask': 2778.34,
 'ytdReturn': None,
 'askSize': 0,
 'volume': 901816472,
 'fiftyTwoWeekHigh': 3393.52,
 'forwardPE': None,
 'maxAge': 1,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': None,
 'fiftyTwoWeekLow': 2280.52,
 'bid': 2316.67,
 'tradeable': False,
 'dividendYield': None,
 'bidSize': 0,
 'dayHigh': 2453.57,
 'exchange': 'SNP',
 'shortName': 'S&P 500',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'INDEX',
 'symbol': '^GSPC',
 'messageBoardId': 'finmb_INDEXGSPC',
 'market': 'us_market',
 'regularMarketPrice': 2436.5,
 'logo_url': ''}

In [4]:
stock.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-02-19,3380.39,3393.52,3378.83,3386.15,3600150000,0,0
2020-02-20,3380.45,3389.15,3341.02,3373.23,4007320000,0,0
2020-02-21,3360.50,3360.76,3328.45,3337.75,3899270000,0,0
2020-02-24,3257.61,3259.81,3214.65,3225.89,4842960000,0,0
2020-02-25,3238.94,3246.99,3118.77,3128.21,5591510000,0,0
2020-02-26,3139.90,3182.51,3108.99,3116.39,5478110000,0,0
2020-02-27,3062.54,3097.07,2977.39,2978.76,7058840000,0,0
2020-02-28,2916.90,2959.72,2855.84,2954.22,8563850000,0,0
2020-03-02,2974.28,3090.96,2945.19,3090.23,6376400000,0,0
2020-03-03,3096.46,3136.72,2976.63,3003.37,6355940000,0,0
2020-03-04,3045.75,3130.97,3034.38,3130.12,5035480000,0,0
2020-03-05,3075.70,3083.04,2999.83,3023.94,5575550000,0,0
2020-03-06,2954.20,2985.93,2901.54,2972.37,6552140000,0,0
2020-03-09,2863.89,2863.89,2734.43,2746.56,8423050000,0,0
2020-03-10,2813.48,2882.59,2734.00,2882.23,7635960000,0,0
2020-03-11,2825.60,2825.60,2707.22,2741.38,7374110000,0,0
2020-03-12,2630.86,2660.95,2478.86,2480.64,8829380000,0,0
2020-03-13,2569.99,2711.33,2492.37,2711.02,8258670000,0,0
2020-03-16,2508.59,2562.98,2380.94,2386.13,7781540000,0,0
2020-03-17,2425.66,2553.93,2367.04,2529.19,8358500000,0,0
2020-03-18,2436.50,2453.57,2280.52,2398.10,901816472,0,0

In [5]:
stock.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1927-12-30,17.66,17.66,17.66,17.66,0,0,0
1928-01-03,17.76,17.76,17.76,17.76,0,0,0
1928-01-04,17.72,17.72,17.72,17.72,0,0,0
1928-01-05,17.55,17.55,17.55,17.55,0,0,0
1928-01-06,17.66,17.66,17.66,17.66,0,0,0
...,...,...,...,...,...,...,...
2020-03-12,2630.86,2660.95,2478.86,2480.64,8829380000,0,0
2020-03-13,2569.99,2711.33,2492.37,2711.02,8258670000,0,0
2020-03-16,2508.59,2562.98,2380.94,2386.13,7781540000,0,0
2020-03-17,2425.66,2553.93,2367.04,2529.19,8358500000,0,0
2020-03-18,2436.50,2453.57,2280.52,2398.10,901816472,0,0

In [6]:
df = stock.history(period="max")

In [7]:
df.head()

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date
1927-12-30  17.66  17.66  17.66  17.66       0          0             0
1928-01-03  17.76  17.76  17.76  17.76       0          0             0
1928-01-04  17.72  17.72  17.72  17.72       0          0             0
1928-01-05  17.55  17.55  17.55  17.55       0          0             0
1928-01-06  17.66  17.66  17.66  17.66       0          0             0

In [8]:
df.tail()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2020-03-12,2630.86,2660.95,2478.86,2480.64,8829380000,0,0
2020-03-13,2569.99,2711.33,2492.37,2711.02,8258670000,0,0
2020-03-16,2508.59,2562.98,2380.94,2386.13,7781540000,0,0
2020-03-17,2425.66,2553.93,2367.04,2529.19,8358500000,0,0
2020-03-18,2436.50,2453.57,2280.52,2398.10,901816472,0,0

In [9]:
stock.financials

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [10]:
IC = stock.financials[stock.financials.columns[::-1]] # Reverse Column

In [11]:
IC

Empty DataFrame
Columns: [Volume, Adj Close, Close, Low, High, Open]
Index: []

In [12]:
IC.loc['Net Income Applicable To Common Shares']

KeyError: 'Net Income Applicable To Common Shares'

In [ ]:
# Change Data object to float
NI = IC.loc['Net Income Applicable To Common Shares'].astype(float)

In [ ]:
plt.plot(NI)
plt.xlabel('Date')
plt.ylabel('Price in millions')
plt.title('Net Income in Yearly')

In [ ]:
stock.balancesheet

In [ ]:
BS = stock.balancesheet.iloc[:,::-1] # Reverse Column

In [ ]:
BS

In [ ]:
BS.loc['Retained Earnings']

In [ ]:
CR = BS.loc['Total Current Assets'].astype(int) / BS.loc['Total Current Liabilities'].astype(int)
CR

In [ ]:
stock.cashflow

In [ ]:
CF = stock.cashflow.loc[::,::-1] # Reverse Column

In [ ]:
CF

## Ratio Analysis

### Short term solvency ratios

In [ ]:
print('Short term solvency ratios')
print('-'*40)
print('Current Ratio')
CR = BS.loc['Total Current Assets'].astype(int) / BS.loc['Total Current Liabilities'].astype(int) # Total Current Assets/Total Current Liabilities
print(CR,"\n")
print('Quick Ratio')
QR = (BS.loc['Total Current Assets'].astype(int) - BS.loc['Inventory'].astype(int)) / BS.loc['Total Current Liabilities'].astype(int) # (Total Current Assets-Inventory)/Total Current Liabilities
print(QR,"\n")
print('Cash Ratio')
CashR = (BS.loc['Cash And Cash Equivalents'].astype(int) - BS.loc['Short Term Investments'].astype(int)) / BS.loc['Total Current Liabilities'].astype(int) # (Cash And Cash Equivalents + Short Term Investments + Intangible Assets)/ Total Current Liabilities)
print(CashR,"\n")
print('Networking Capital to Current Liabilities')
NCCL = (BS.loc['Total Current Assets'].astype(int) - BS.loc['Total Current Liabilities'].astype(int)) / BS.loc['Total Current Liabilities'].astype(int) # (Total Current Assets - Total Current Liabilities)/Total Current Liabilities)
print(NCCL,"\n")

### Asset Utilization or Turnover ratios

In [ ]:
print('Asset Utilization or Turnover ratios')
print('-'*40)
print('Average Collection Period')
ACP = BS.loc['Net Receivables'].astype(int) / (IC.loc['Total Revenue'].astype(int)/360) # Net Receivables/(Total Revenue/360)
print(ACP,"\n")
print('Inventory Turnover Ratios')
ITR = IC.loc['Total Revenue'].astype(int) / BS.loc['Inventory'].astype(int)# Total Revenue / Inventory
print(ITR,"\n")                                             
print('Receivable Turnover')
RT = IC.loc['Total Revenue'].astype(int)/BS.loc['Net Receivables'].astype(int) # Total Revenue / Net Receivables
print(RT,"\n")                                                     
print('Fixed Asset Turnover')
FAT = IC.loc['Total Revenue'].astype(int)/BS.loc['Net Receivables'].astype(int) # Total Revenue / Property, plant and equipment
print(FAT,"\n")   
print('Total Asset Turnover')                                             
TAT = IC.loc['Total Revenue'].astype(int)/BS.loc['Total Assets'].astype(int)# Total Revenue / Total Assets
print(TAT,"\n")

### Financial Leverage ratios

In [ ]:
print('Financial Leverage ratios')
print('-'*40)
print('Total Debt Ratio')
TDR = BS.loc['Total Liabilities'].astype(int) / BS.loc['Total Assets'].astype(int) # Total Liabilities / Total Assets
print(TDR,"\n")
print('Debt/Equity')
DE = BS.loc['Total Liabilities'].astype(int) / BS.loc["Total stockholders' equity"].astype(int) # Total Liabilities / Total stockholders' equity
print(DE,"\n")
print('Equity Ratio')
ER = BS.loc["Total stockholders\' equity"].astype(int) / BS.loc['Total Assets'].astype(int) # Total stockholders' equity / Total Assets
print(ER,"\n")
print('Long-term Debt Ratio')
LTDR = BS.loc['Long Term Debt'].astype(int) / BS.loc['Total Assets'].astype(int) # Long Term Debt / Total Assets
print(LTDR,"\n") 
print('Times Interest Earned Ratio')
TIER = IC.loc['Earnings Before Interest and Taxes'].astype(int) / IC.loc['Interest Expense'].astype(int) # Earnings Before Interest and Taxes / Interest Expense
print(TIER,"\n")

### Profitability ratios

In [ ]:
print('Profitability ratios')
print('-'*40)
print('Gross Profit Margin')
GPM = IC.loc['Gross Profit'].astype(int) / IC.loc['Total Revenue'].astype(int) # Gross Profit / Total Revenue
print(GPM,"\n") 
print('Net Profit Margin')
NPM = IC.loc['Net Income Applicable To Common Shares'].astype(int) / IC.loc['Total Revenue'].astype(int) # Net Income / Total Revenue
print(NPM,"\n") 
print('Return on Assets (ROA)')
ROA = IC.loc['Net Income Applicable To Common Shares'].astype(int) / BS.loc['Total Assets'].astype(int) # Net Income / Total Assets
print(ROA,"\n") 
print('Return on Equity (ROE)')
ROE = IC.loc['Net Income Applicable To Common Shares'].astype(int) / BS.loc['Total stockholders\' equity'].astype(int) # Net Income / Total Equity
print(ROE,"\n") 
print('Earning Per Share (EPS)')
EPS = IC.loc['Net Income Applicable To Common Shares'].astype(int) / (BS.loc['Common Stock'].astype(int) - BS.loc['Treasury Stock'].astype(int)) # Net Income / (Common Stock - Treasury Stock)
print(EPS,"\n")